### ISSUE TITLE
BUG: Tabs do not update with programmatic setting of Vue ref

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/miter-design#125]
The `Tabs` component styling doesn't update when a Vue ref is passed and changed programmatically, e.g.:
```vue
<template>
  <Tabs v-model="tab">
     <Tab href="tab_1">Tab 1</Tab>
     <Tab href="tab_2">Tab 2</Tab>
  </Tabs>

  <button @click="changeTabs">Change tabs</button>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const tab = ref('tab_1')

const changeTabs = () => {
  tab.value = tab.value == 'tab_1' ? 'tab_2' : 'tab_1'
}
</script>
```

**Comment by pleek91** [comment]
@marichka-offen looking at this it looks like Tabs.vue accepts a modeValue prop but never reacts to it after initial render. Updating the component to use a get/set computed for the active tab should fix this.

**Comment by znicholasbrown** [comment]
Absolutely do not git blame that component to see who made that oversight 😅
