### ISSUE TITLE
can't use `<m-text-area>`?

### ISSUE THREAD

**Issue by stackoverfloweth** [PrefectHQ/miter-design#208]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/6098901/157101035-f8d2b8ff-f22b-4a30-8838-f4b651033457.png">

**Comment by ThatGalNatalie** [comment]
I ran into the same issue and already created an issue for it [here](https://github.com/PrefectHQ/miter-design/issues/187)

**Comment by stackoverfloweth** [comment]
closing as duplicate of #187
